[package]
name = "yee-jsonrpc-types"
version = "0.4.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
numext-fixed-hash = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"] }
numext-fixed-uint = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
faster-hex = "0.3"
jsonrpc-core = "10.1"
bytes = { version="0.4.12", features = ["serde"] }

