[package]
name = "yee-switch-rpc"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
error-chain = "0.12"
jsonrpc-core = "10.0.1"
jsonrpc-pubsub = "10.0.1"
jsonrpc-derive = "10.0.1"
jsonrpc-core-client = "12.1.0"
jsonrpc-client-transports = "12.1.0"
log = "0.4"
parking_lot = "0.7.1"
parity-codec = "3.2"
serde = { version = "1.0", features = ["derive"] }
impl-serde = { version = "0.1"}
serde_json = "1.0"
primitives = { package = "substrate-primitives", git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0" }
runtime_primitives = { package = "sr-primitives", git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0" }
runtime_version = { package = "sr-version", git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0" }
substrate-cli = { git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0" }
sr-io = { git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0" }
yee-runtime = { package = "yee-runtime", path = "../../runtime" }
yee-sharding-primitives= { package = "yee-sharding-primitives", path = "../../core/sharding/primitives" }
tokio = "0.1.7"
futures = "0.1.17"
hex-literal = "0.1"
rustc-hex = "2.0"
rand = "0.6.5"
num-bigint = "0.2.2"
hex = "0.3.2"
yee-serde-hex = { package = "yee-serde-hex", path = "../../rpc/serde-hex" }

[features]
http = []

