[package]
name = "yee-foreign-chain"
version = "0.4.0"
authors = ["YeeCo <contact@yeefoundation.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exit-future = "0.1"
log = "0.4"
tokio = "0.1.7"
sharding_primitives = { package = "yee-sharding-primitives", path = "../../core/sharding/primitives" }
inherents = { package = "substrate-inherents", git = "https://github.com/yeeco/substrate.git", branch = "gb/exit-signal" }
keystore = { package = "substrate-keystore", git = "https://github.com/yeeco/substrate.git", branch = "gb/exit-signal" }
network = { package = "substrate-network", git = "https://github.com/yeeco/substrate.git", branch = "gb/exit-signal" }
rpc = { package = "substrate-rpc-servers", git = "https://github.com/yeeco/substrate.git", branch = "gb/exit-signal" }
runtime_primitives = { package = "sr-primitives", git = "https://github.com/yeeco/substrate.git", branch = "gb/exit-signal" }
substrate-client = { git = "https://github.com/yeeco/substrate.git", branch = "gb/exit-signal" }
substrate-service = { git = "https://github.com/yeeco/substrate.git", branch = "gb/exit-signal" }
transaction_pool = { package = "substrate-transaction-pool", git = "https://github.com/yeeco/substrate.git", branch = "gb/exit-signal" }
