[package]
name = "yee-consensus-pow-primitives"
version = "0.1.0"
authors = ["YeeCo <contact@yeefoundation.com>"]
edition = "2018"

[dependencies]
primitives = { package = "substrate-primitives", git = "https://github.com/yeeco/substrate.git", default_features = false, branch = "mn/v1.2" }
runtime_primitives = { package = "sr-primitives", git = "https://github.com/yeeco/substrate.git", default_features = false, branch = "mn/v1.2" }
substrate-client = { git = "https://github.com/yeeco/substrate.git", default_features = false, branch = "mn/v1.2" }

[features]
default = ["std"]
std = [
    "primitives/std",
    "runtime_primitives/std",
    "substrate-client/std",
]
