[package]
name = "yee-sharding-primitives"
version = "0.1.0"
authors = ["YeeCo <contact@yeefoundation.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primitives = { package = "substrate-primitives", git = "https://github.com/yeeco/substrate.git", default_features = false, branch = "yee-v1.0" }
runtime_primitives = { package = "sr-primitives", git = "https://github.com/yeeco/substrate.git", default_features = false, branch = "yee-v1.0" }
substrate-client = { git = "https://github.com/yeeco/substrate.git", default_features = false, branch = "yee-v1.0" }
parity-codec = { version = "3.2", default-features = false, features = ["derive"] }

[dev-dependencies]
yee-runtime = { package = "yee-runtime", path = "../../../runtime" }
hex = "0.3.1"

[features]
default = ["std"]
std = [
    "primitives/std",
    "runtime_primitives/std",
    "substrate-client/std",
    "parity-codec/std",
]
