[package]
name = "yee-serde-hex"
version = "0.4.0"
authors = ["YeeCo <contact@yeefoundation.com>"]
edition = "2018"

[dependencies]
smallvec = "0.6"
serde = { version = "1.0", features = ["derive"] }
impl-serde = "0.1"
num-bigint = "0.2.2"

[dev-dependencies]
serde_json = "1.0"
