[package]
name = "yee-merkle"
version = "0.4.0"
authors = ["YeeCo <contact@yeefoundation.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rstd = { package = "sr-std", git = "https://github.com/yeeco/substrate.git", rev = "24b6e10cdd091029e29df68ac7fecfc62c6c7d76", default-features = false }
parity-codec = { version = "3.2", default-features = false }
runtime_primitives = { package = "sr-primitives", git = "https://github.com/yeeco/substrate.git", rev = "24b6e10cdd091029e29df68ac7fecfc62c6c7d76", default-features = false }
merkle-light = { package = "merkle_light", git = "https://github.com/yeeco/merkle_light.git", branch = "yee", default-features = false }
log = { version = "0.4", optional = true }

[features]
default = ["std"]
std = [
	"parity-codec/std",
	"runtime_primitives/std",
	"merkle-light/std",
	"log",
]
