[package]
name = "yee-sr-primitives"
version = "0.4.0"
authors = ["YeeCo <contact@yeefoundation.com>"]
edition = "2018"

[dependencies]
rstd = { package = "sr-std", git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0", default-features = false }
parity-codec = { version = "3.5", default-features = false, features = ["derive"] }
substrate-primitives = { package = "substrate-primitives", git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0", default-features = false }


[features]
default = ["std"]
std = [
    "rstd/std",
	"parity-codec/std",
]
