[package]
name = "util"
version = "0.4.0"
authors = ["YeeCo <contact@yeefoundation.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parity-codec = "3.5"
rstd = { package = "sr-std", git = "https://github.com/yeeco/substrate.git", default-features = false, rev = "e015c881080fbef2733413eb0fb5864b9c272797" }
primitives = { package = "sr-primitives", git = "https://github.com/yeeco/substrate.git", default-features = false, rev = "e015c881080fbef2733413eb0fb5864b9c272797" }
substrate-primitives = { package = "substrate-primitives", git = "https://github.com/yeeco/substrate.git", rev = "e015c881080fbef2733413eb0fb5864b9c272797", default-features = false }
